package com.store.shopping_cart.shoppingcart.dto;


import com.store.shopping_cart.shoppingcart.security.dto.UserResponse;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@RequiredArgsConstructor
@Setter
@Getter
@ToString
public class OrderRequest {
    @Schema(name = "idOrder",required = false,example = "1",defaultValue = "2",description = "This key is autogenerated, it's not necesary")
    private Integer idOrder;
    @Schema(name = "totalAmount",required = false,example = "1",defaultValue = "2",description = "This key is autocalculate, it's not necesary")
    @Min(0)
    private double totalAmount;
    @Schema(name = "totalAmount",required = false,example = "1",defaultValue = "2",description = "this key is to indicate, total items of order")
    @Min(1)
    private int totalItems;
    @Schema(name = "status",required = true,example = "in progress",defaultValue = "in progress",description = "this key indicates the status of the order")
    @NotBlank
    private String status;
    @Schema(name = "idUser", example = "{\"userId\":1,\"name\":\"MauricioSanchez\",\"email\":\"mauricio.sanchez@gmail.com\",\"username\":\"msanchez\",\"active\":true,\"roles\":[{\"roleId\":3,\"roleName\":\"CLIENT_ROLE\"}]}" , required = true,description = "this key indicates the user")
    @NotNull
    private UserResponse idUser;

    @Schema(name = "idPayment",required = true,example = "\"{\\\"idPayment\\\":3,\\\"paymentType\\\":\\\"DEBIT_CARD\\\",\\\"status\\\":\\\"PENDING\\\",\\\"creatDate\\\":\\\"2024-01-29T17:04:45.566+00:00\\\",\\\"updateDate\\\":\\\"2024-01-29T17:04:45.566+00:00\\\"}\"",description = "this key indicates payment")
    @Nullable
    private PaymentResponse idPayment;
}
