package com.store.shopping_cart.shoppingcart.dto;


import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@RequiredArgsConstructor
@Setter
@Getter
public class OrderDetailDto {
    @Schema(name = "idOrderDetail",required = false,example = "1",defaultValue = "2",description = "This key is autogenerated, it's not necesary")
    private Integer idOrderDetail;
    @Schema(name = "quantity",required = true,example = "1",defaultValue = "2",description = "this key is to indicate the quantity of products")
    @Min(1)
    private int quantity;
    @Schema(name = "amount",required = false,example = "1",defaultValue = "0",description = "this key is to indicate the amount of detail")
    @Min(0)
    private double amount;
    @Schema(name = "productId",required = true,example = "1",defaultValue = "2",description = "this key is to indicate the id of product")
    @NotNull
    private ProductResponse productId;
    @Schema(name = "productPrice",required = true,example = "14.15",defaultValue = "10.0",description = "this key is to indicate the product price")
    @Min(0)
    private double productPrice;
    @Schema(name = "idOrder",required = true,example = "1",defaultValue = "2",description = "this key is to indicate the id order")
    @NotNull
    private OrderResponse idOrder;
}
