package com.store.shopping_cart.shoppingcart.dto;

import java.util.Date;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@RequiredArgsConstructor
@Setter
@Getter
public class PaymentResponse {
    @Schema(name = "idPayment",required = false,example = "1",defaultValue = "2",description = "This key is autogenerated, it's not necesary")
    private Integer idPayment;
    @Schema(name = "idOrder",required = true,example = "1",defaultValue = "2",description = "this key is to indicate the id order")
    private OrderResponse idOrder;
    @Schema(name = "paymentType",required = true,example = "cash",defaultValue = "cash",description = "this key is to indicate the payment type")
    private String paymentType;
    @Schema(name = "status",required = true,example = "pending",defaultValue = "pending",description = "this key indicates the status of the payment")
    private String status;
    @Schema(name = "creatDate",required = true,example = "",defaultValue = "",description = "this key indicates payment creation date")
    private Date creatDate;
    @Schema(name = "updateDate",required = true,example = "",defaultValue = "",description = "this key indicates payment update date")
    private Date updateDate;

}
